# Generated by Django 4.0.5 on 2022-07-06 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miRastra', '0004_delete_rastra_alter_user_options_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rastra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('is_active', models.BooleanField(default=False, null=True, verbose_name='Is_active')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('stars', models.FloatField(default='Stars')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='Description')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Rastra',
                'verbose_name_plural': 'Rastras',
            },
        ),
    ]
