# Generated by Django 4.0.5 on 2022-07-08 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miRastra', '0005_rastra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rastra',
            name='stars',
        ),
        migrations.AddField(
            model_name='rastra',
            name='direction',
            field=models.CharField(max_length=500, null=True, verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='rastra',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('rastra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miRastra.rastra', verbose_name='Rastra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0, verbose_name='Stars')),
                ('comment', models.CharField(max_length=500, verbose_name='Comment')),
                ('rastra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miRastra.rastra', verbose_name='Rastra')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
    ]
