# Generated by Django 4.0.5 on 2022-07-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miRastra', '0006_remove_rastra_stars_rastra_direction_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rastra',
            name='state',
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
