# Generated by Django 4.0.5 on 2022-07-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miRastra', '0009_alter_rating_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='Stars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Supplier')], verbose_name='Type'),
        ),
    ]
