# Generated by Django 4.0.5 on 2022-07-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miRastra', '0010_alter_rating_stars_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Supplier'), (3, 'Admin')], default=3, verbose_name='Type'),
        ),
    ]
