# Generated by Django 4.0.5 on 2022-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miRastra', '0011_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_active',
            field=models.BooleanField(default=False, null=True, verbose_name='Is_active'),
        ),
    ]
