# Generated by Django 4.0.5 on 2022-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miRastra', '0012_reservation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is_active'),
        ),
    ]
