# Generated by Django 4.0.5 on 2022-07-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miRastra', '0017_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
