# Generated by Django 4.0.5 on 2022-07-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miRastra', '0019_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='time',
            new_name='finish',
        ),
    ]
