# Generated by Django 4.0.5 on 2022-07-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miRastra', '0022_alter_user_options_alter_reservation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('PD', 'Pendiente...'), ('AC', 'Activo'), ('FN', 'Finalizado'), ('CL', 'Cancelado')], default='PD', max_length=20),
        ),
    ]
