# Generated by Django 4.0.5 on 2022-07-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miRastra', '0024_alter_reservation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='state',
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.DateField()),
                ('state', models.CharField(choices=[('Pendiente...', 'Pendiente...'), ('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Pendiente...', max_length=20)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miRastra.reservation', verbose_name='Reservación')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
