# Generated by Django 4.0.5 on 2022-07-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miRastra', '0028_alter_reservation_state_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activa', 'Activa'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
